theme: jekyll-theme-minimal
title: Welcome to Ranjit's Page
description: Robotic Systems Engineer <br /> _Best viewed in Desktop_
             santhanaraman.ranjit@rwth-aachen.de 
             <iframe src="https://drive.google.com/file/d/1dZATY7OujDIYFjN4QZNkt0ep5KnZ82Xi/preview" width="300" height="200"></iframe>
