theme: jekyll-theme-minimal
title: Welcome to Ranjit's Page
description: Passionate drone designer and developer. <br /> (Best viewed in Desktop)
             vsranjitroshan@gmail.com 
             <iframe src="https://drive.google.com/file/d/1dZATY7OujDIYFjN4QZNkt0ep5KnZ82Xi/preview" width="300" height="200"></iframe>
