theme: jekyll-theme-minimal
title: Welcome to Ranjit's Page
description: Passionate drone designer and developer. <br />
             vsranjitroshan@gmail.com 
             <iframe src="https://drive.google.com/file/d/1DOnnQ1ERndXi7IeG9XGoDxqWQ-QHE4rv/preview" width="300" height="240"></iframe>
             <iframe src="https://drive.google.com/file/d/1cYAspavME3v48QGeK7C_C9BaFqZSH__D/preview" width="300" height="240"></iframe>
