theme: jekyll-theme-minimal
title: Welcome to Ranjit's Page
description: Passionate drone designer and developer. <br />
             vsranjitroshan@gmail.com 
             <iframe src="https://drive.google.com/file/d/1DOnnQ1ERndXi7IeG9XGoDxqWQ-QHE4rv/preview" width="240" height="80"></iframe>
